# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipc/visualisation/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eipc/visualisation/common.proto\x12\x11ipc.visualisation\"\x07\n\x05\x45mpty\"\x1e\n\rParticleIndex\x12\r\n\x05index\x18\x01 \x01(\x03\x42$Z\"./generated/ipc/visualisation_api/b\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_PARTICLEINDEX = DESCRIPTOR.message_types_by_name['ParticleIndex']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'ipc.visualisation.common_pb2'
  # @@protoc_insertion_point(class_scope:ipc.visualisation.Empty)
  })
_sym_db.RegisterMessage(Empty)

ParticleIndex = _reflection.GeneratedProtocolMessageType('ParticleIndex', (_message.Message,), {
  'DESCRIPTOR' : _PARTICLEINDEX,
  '__module__' : 'ipc.visualisation.common_pb2'
  # @@protoc_insertion_point(class_scope:ipc.visualisation.ParticleIndex)
  })
_sym_db.RegisterMessage(ParticleIndex)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"./generated/ipc/visualisation_api/'
  _EMPTY._serialized_start=53
  _EMPTY._serialized_end=60
  _PARTICLEINDEX._serialized_start=62
  _PARTICLEINDEX._serialized_end=92
# @@protoc_insertion_point(module_scope)
