# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipc/visualisation/empty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dipc/visualisation/empty.proto\x12\x11ipc.visualisation\"\x07\n\x05\x45mptyB$Z\"./generated/ipc/visualisation_api/b\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'ipc.visualisation.empty_pb2'
  # @@protoc_insertion_point(class_scope:ipc.visualisation.Empty)
  })
_sym_db.RegisterMessage(Empty)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"./generated/ipc/visualisation_api/'
  _EMPTY._serialized_start=52
  _EMPTY._serialized_end=59
# @@protoc_insertion_point(module_scope)
