# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ipc.visualisation import empty_pb2 as ipc_dot_visualisation_dot_empty__pb2
from ipc.visualisation import visualisation2D_pb2 as ipc_dot_visualisation_dot_visualisation2D__pb2


class Particle2DObserverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObserveParticle = channel.unary_unary(
                '/ipc.visualisation.Particle2DObserver/ObserveParticle',
                request_serializer=ipc_dot_visualisation_dot_visualisation2D__pb2.Particle2D.SerializeToString,
                response_deserializer=ipc_dot_visualisation_dot_empty__pb2.Empty.FromString,
                )


class Particle2DObserverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObserveParticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Particle2DObserverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObserveParticle': grpc.unary_unary_rpc_method_handler(
                    servicer.ObserveParticle,
                    request_deserializer=ipc_dot_visualisation_dot_visualisation2D__pb2.Particle2D.FromString,
                    response_serializer=ipc_dot_visualisation_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ipc.visualisation.Particle2DObserver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Particle2DObserver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObserveParticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ipc.visualisation.Particle2DObserver/ObserveParticle',
            ipc_dot_visualisation_dot_visualisation2D__pb2.Particle2D.SerializeToString,
            ipc_dot_visualisation_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
